### ISSUE TITLE
"review 1", "review 2", tags created in Evernote after running script

### ISSUE THREAD

**Issue by tajchiu** [frankmeeuwsen/Evernote2Omnifocus#3]
Thank you so much for writing this script. I am having a problem that I can't figure out how to solve though. After I run the script new tags are created - "review 1" and then "review 2" and so on. I would prefer for either the review tag to remain (ideal) or for there to be no new "review 1" tags and so on.

**Comment by frankmeeuwsen** [comment]
I had the same problem and couldn't solve it. I think it has something to
do with synchronization issues where Evernote automatically makes new
"review" tags. I am not quite sure.

Frank

Op zaterdag 18 april 2015 heeft tajchiu <notifications@github.com> het
volgende geschreven:

> Thank you so much for writing this script. I am having a problem that I
> can't figure out how to solve though. After I run the script new tags are
> created - "review 1" and then "review 2" and so on. I would prefer for
> either the review tag to remain (ideal) or for there to be no new "review
> 1" tags and so on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frankmeeuwsen/Evernote2Omnifocus/issues/3>.
>


-- 
Met vriendelijke groet,
Frank Meeuwsen

**Comment by tajchiu** [comment]
It least it isn't just me!

Taj

--

Taj Chiu | CEO/Co-Founder
toybuilderlabs.com
<http://t.strk04.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX48ql-10W1pNBQj653cMlW4Wzrfn56dTBvf4fjkvj02?t=http%3A%2F%2Fwww.toybuilderlabs.com%2F&si=4726946735325184&pi=bb3454f7-efc3-4f04-8b84-4000fd8626d3>
1848 E Walnut St Pasadena, CA 91107
T +1 626 808 4010 x.700     I    E taj@toybuilderlabs.com    I    S tajchiu

**Comment by tbenst** [comment]
I think this code will solve it (courtesy of [Justin Lancy](http://veritrope.com/code/get-note-links-in-evernote-for-newly-created-notes/)

    --TEST TO SEE IF EVERNOTE IS CURRENTLY SYNCHRONIZING...
    repeat until isSynchronizing is false
        --THIS EMPTY LOOP WILL PAUSE SCRIPT UNTIL PREVIOUS SYNC IS FINISHED
    end repeat
