### ISSUE TITLE
review tag no longer being removed

### ISSUE THREAD

**Issue by toddalopolis** [frankmeeuwsen/Evernote2Omnifocus#4]
Hi, getting multiple identical entries into the Omnifocus inbox - for some reason the "review" tag is no longer being removed. Also getting "Evernote...not found" errors.
Using Lingon 3.1.3, Omnifocus 2.2.4, Evernote 6.0.5, Outlook 2011 14.5.4
Thanks.

**Comment by frankmeeuwsen** [comment]
I encountered the issue myself as well but can't find a way to fix it properly. It looks like a synchronisation issue where the tag is not removed properly and added again. If you find a way to fix it, please share it here.

**Comment by idlebook** [comment]
Hi, this script help me lot,  but many tasks include pictures and audio files, which are not imported into Evernote. I tried to use Applescript to modify and consult the documents, but I couldn't solve it all the time. Can you help me solve this problem in leisure?
I look forward to your reply!
