### ISSUE TITLE
imported EverNote with attachment

### ISSUE THREAD

**Issue by idlebook** [frankmeeuwsen/Evernote2Omnifocus#5]
Hi, this script help me lot, but many tasks include pictures and audio files, which are not imported into Evernote. I want to make this script more perfect, so I tried to use AppleScript to modify and consult the documents, but I couldn't solve it all the time.Can you take a some time consider improve this script? Thanks!

I look forward to your reply!

**Comment by frankmeeuwsen** [comment]
This script is meant to make a link between your Evernote note and the Omnifocus task. So nothing is imported into Evernote. If you have a note in Evernote with pictures and audio, you can link it to an Omnifocus task. In Omnifocus you can find a link back to the Evernote task with all the attachments you need.

**Comment by idlebook** [comment]
Thanks for you help, I know what to do.
